### ISSUE TITLE
Plugin saves a ~/D:\multibuffer

### ISSUE THREAD

**Issue by pcav** [havatv/qgismultidistancebufferplugin#1]
This seems inappropriate, particularly for non-Windows systems

**Comment by havatv** [comment]
Thank you for reporting.  May be I don't understand the question, but saving of temporary files is done to a temporary directory found using Python't tempfile module, and I thought that this should be portable.  I don't have any problems on Windows or Ubuntu.  I don't have access to MacOS.

**Comment by pcav** [comment]
The appropriate dir would be /temp. In your case, it goes to ~/D:\multibuffer

**Comment by havatv** [comment]
On which platform are you?
Which dataset is it that goes to ~/D:\multibuffer?

**Comment by pcav** [comment]
Debian sid
Dir empty, apparently is created at plugin import

**Comment by havatv** [comment]
OK.  I will inspect the code to see what the reason for this can be. Thanks again for reporting.

**Comment by havatv** [comment]
I am not able to find any trace of "multibuffer" or "D:" in the plugin files.
I tried to uninstall and install the plugin with QGIS 2.8.2 on Ubuntu 14.04, but after import I found nothing that looked like ~/D:\multibuffer.
Nothing happens when I start QGIS and the plugin.
So this is very strange. Can you try to reproduce it?

**Comment by pcav** [comment]
Just tested:
- rm ~/D:\multibuffer
- started QGIS, with Multi-distance buffer v 0.1 installed
- ~/D:\multibuffer is created straight away.
  Debian sid, QGIS 2.8.4.
  Thanks.

**Comment by havatv** [comment]
Very strange, indeed.
Could there be other plugins that are causing this?
What happens if you first uninstall the Multi-distance buffer plugin, then remove the strange directory (~/D:\multibuffer) and finally restart QGIS?

**Comment by pcav** [comment]
Oho, you seem to be right! Uninstalling the plugin, rm the dir, restarting qgis recreates the dir again. So it must be something else, unclear what. Sorry about the noise, but the name really pushed be on the wrong track.

**Comment by havatv** [comment]
Thanks for clarifying!  And good to hear that it was a false alarm this time.

**Comment by havatv** [comment]
The previous commit was supposed to reference issue #2!
