### ISSUE TITLE
Less useful in QGIS3?

### ISSUE THREAD

**Issue by pcav** [havatv/qgismultidistancebufferplugin#11]
Please note that Processing in QGIS3 allows apparently the same analysis.

**Comment by havatv** [comment]
That sound interesting. I tried to find it by searching in the processing toolbox, but was not able to (2.99.0-master, code revision 5ef16bf).  Could you help me locating it?

**Comment by pcav** [comment]
Now Processing can accept expressions as parameters, so the user can calculate their own variables.

**Comment by havatv** [comment]
I guess that "normal" users would want to find a "function" for doing multi-distance buffering.  How would you suggest we provide them with this with the QGIS 3 Processing opportunities?

**Comment by havatv** [comment]
I may have misunderstood you.  Did you mean that there is no longer a need for this plugin in processing (#7)?

**Comment by pcav** [comment]
Apparently yes. Usability, as you have pointed out, should be checked, however.
The current approach in Processing is very powerful and generic, and it *should* do all what is needed.

**Comment by havatv** [comment]
OK.  So I guess that for users that are not using Processing for "programming", there may still be a need for this plugin (outside Processing).

**Comment by pcav** [comment]
It should not be. At least, this is not the aim, as I understand it. To me the current situation in Processing is good enough; what could be missing is a series of preset functions to help users choosing their variable buffer without the need to learn too much about expressions.
Would you mind raising this on `qgis-dev` mailing list?
Thanks.

**Comment by havatv** [comment]
Multi-distance buffering without the help of a plugin has always been possible in QGIS by combining a number of fixed distance buffers using geometric subtraction. It is and has been possible to do this also in Processing.
The multi-distance buffer plugin is a utility to help those that need this function occasionally or are too lazy (or incompetent) to do this process.  That there are two plugins ("Multi-distance buffer" and "Multi Ring Buffer") for this, both with more than 10,000 downloads, indicate that it is useful to some.
So I guess that there will continue to be a need for this function in QGIS.  It is therefore important that it is easily available in QGIS3, and to make it easily available I think that it needs to be exposed as a user-level function with a recognisable name (through Processing or otherwise).

I am afraid I don't yet understand what you would like me to raise on qgis-dev.

**Comment by pcav** [comment]
Sorry I was unclear. The Grand Plan is to reduce duplication of code, functions, and menus, and to concentrate as much as possible into Processing, so I just wondered if there is a way to do this without making things more complex for the user.
I started a discussion on qgis-dev myself, I'd appreciate if you could join in.
Of course, I have published your plugin, we're just talking about possible improvements for the future.

**Comment by havatv** [comment]
I don't know much about Processing or expressions as parameters - I hope you can forgive my ignorance.
My problem is that with my lack of knowledge I have not understood how the multi-distance buffer "function" can be made easily available through Processing.  The important thing is to make it easy for users to input an unknown set of numbers and then return a multi-distance buffer (consisting of as many "zones" as there are numbers).

**Comment by pcav** [comment]
agreed fully. let's see if we can design in Processing an easy way to do this. are you following the discussion on qgis-dev?
thanks.

**Comment by havatv** [comment]
Yes.  And I would like to help, but then I need to learn more.

**Comment by havatv** [comment]
An important feature of multi-distance buffering is that the buffer zone of each generated (multi)polygon must be identifiable, preferably with attributes containing the inner and outer size of the buffer.  How would you obtain that without a plugin or a processing script in QGIS 3?

**Comment by pcav** [comment]
I think adding this function to Processing should be straightforward. Please ask qgis-dev mailing list for guidelines and examples.
Thanks a lot.

**Comment by havatv** [comment]
It is probably trivial to also have it as a processing plugin. I guess / hope that tutorials on how to add processing support for plugins will become available when QGIS 3 has been released.

**Comment by pcav** [comment]
Possibly. Much better though if you raise the question on qgis-dev mailing list.
Thanks.

**Comment by havatv** [comment]
I think I have understood more about the processing improvements for QGIS 3, including support for expressions as parameters.  As far as I can tell, this makes it possible to create multiple buffers, but not non-overlapping zones with attributes identifying the zones.
I think this answers the original question - Processing in QGIS3 does not allow the same analysis, at least not as one "operation".  The plugin is therefore useful also in QGIS3.
The issue of moving to processing is covered by issue #7, so I will close this one.
