### ISSUE TITLE
Insufficient Decimal Points for Buffer Distance

### ISSUE THREAD

**Issue by SteveEdiger** [havatv/qgismultidistancebufferplugin#4]
Decimal points are limited to tenths, which in the map I'm working on makes the buffer zone in tens of miles.  My current project demands a buffer zone of blocks.

**Comment by havatv** [comment]
Thanks for reporting.  I will try to fix it soon.

**Comment by havatv** [comment]
@SteveEdiger, how many decimals do you need?

**Comment by havatv** [comment]
Changed from one to nine decimals.

**Comment by havatv** [comment]
The change is available in version 1.0 of the plugin that has just now been uploaded to http://plugins.qgis.org.
